set(_CATKIN_CURRENT_PACKAGE "cse_190_assi_1")
set(cse_190_assi_1_MAINTAINER "sean <sean@todo.todo>")
set(cse_190_assi_1_DEPRECATED "")
set(cse_190_assi_1_VERSION "0.0.0")
set(cse_190_assi_1_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(cse_190_assi_1_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(cse_190_assi_1_BUILDTOOL_DEPENDS "catkin")